server:
  port: 8181
  error:
    include-message: ALWAYS

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  datasource:
    url: jdbc:h2:mem:customer_rewards
    driver-class-name: org.h2.Driver
    username: vishnu
    password: vishnu
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: customer-rewards-api


